
-- Create Addresses --

SET ANSI_NULLS ON;

SET QUOTED_IDENTIFIER ON;

CREATE TABLE [dbo].[ADDRESSES](
	[ADDRESS_ID] [varchar](256) NOT NULL,
	[ZIPCODE] [numeric](38, 0) NULL,
	[COUNTRY] [varchar](256) NULL,
	[ADDRESS] [varchar](256) NULL,
	[STATE] [varchar](256) NULL,
 CONSTRAINT [PK_ADDRESSES] PRIMARY KEY CLUSTERED 
(
	[ADDRESS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];

-- Create Events --

SET ANSI_NULLS ON;

SET QUOTED_IDENTIFIER ON;

CREATE TABLE [dbo].[EVENTS](
	[EVENT_ID] [varchar](1024) NOT NULL,
	[PAGE_URL] [varchar](1024) NULL,
	[EVENT_TYPE] [varchar](100) NULL,
	[USER_ID] [varchar](1024) NULL,
	[PRODUCT_ID] [varchar](1024) NULL,
	[SESSION_ID] [varchar](1024) NULL,
	[CREATED_AT] [datetime] NULL,
	[ORDER_ID] [varchar](1024) NULL
 CONSTRAINT [PK_EVENTS] PRIMARY KEY CLUSTERED 
(
	[EVENT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];

-- Create ORDER_ITEMS --
SET ANSI_NULLS ON;

SET QUOTED_IDENTIFIER ON;

CREATE TABLE [dbo].[ORDER_ITEMS](
	[ORDER_ID] [varchar](256) NOT NULL,
	[PRODUCT_ID] [varchar](256) NOT NULL,
	[QUANTITY] [numeric](38, 0) NULL
 CONSTRAINT [PK_ORDER_ITEMS] PRIMARY KEY CLUSTERED 
(
	[ORDER_ID] ASC,
	[PRODUCT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];

-- Create ORDERS --

SET ANSI_NULLS ON;

SET QUOTED_IDENTIFIER ON;

CREATE TABLE [dbo].[ORDERS](
	[ORDER_ID] [varchar](256) NOT NULL,
	[SHIPPING_SERVICE] [varchar](256) NULL,
	[SHIPPING_COST] [float] NULL,
	[ADDRESS_ID] [varchar](256) NULL,
	[CREATED_AT] [datetime] NULL,
	[PROMO_ID] [varchar](256) NULL,
	[ESTIMATED_DELIVERY_AT] [datetime] NULL,
	[ORDER_COST] [float] NULL,
	[USER_ID] [varchar](256) NULL,
	[ORDER_TOTAL] [float] NULL,
	[DELIVERED_AT] [datetime] NULL,
	[TRACKING_ID] [varchar](256) NULL,
	[STATUS] [varchar](256) NULL
 CONSTRAINT [PK_ORDERS] PRIMARY KEY CLUSTERED 
(
	[ORDER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];

-- Create PRODUCTS --

SET ANSI_NULLS ON;

SET QUOTED_IDENTIFIER ON;

CREATE TABLE [dbo].[PRODUCTS](
	[PRODUCT_ID] [varchar](256) NOT NULL,
	[PRICE] [float] NULL,
	[NAME] [varchar](256) NULL,
	[INVENTORY] [numeric](38, 0) NULL
 CONSTRAINT [PK_PRODUCTS] PRIMARY KEY CLUSTERED 
(
	[PRODUCT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];

-- Create PROMOS --

SET ANSI_NULLS ON;

SET QUOTED_IDENTIFIER ON;

CREATE TABLE [dbo].[PROMOS](
	[PROMO_ID] [varchar](256) NOT NULL,
	[DISCOUNT] [numeric](38, 0) NULL,
	[STATUS] [varchar](256) NULL,
 CONSTRAINT [PK_PROMOS] PRIMARY KEY CLUSTERED 
(
	[PROMO_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];

-- Create Users --

SET ANSI_NULLS ON;

SET QUOTED_IDENTIFIER ON;

CREATE TABLE [dbo].[USERS](
	[USER_ID] [varchar](256) NOT NULL,
	[UPDATED_AT] [datetime] NULL,
	[ADDRESS_ID] [varchar](256) NULL,
	[LAST_NAME] [varchar](256) NULL,
	[CREATED_AT] [datetime] NULL,
	[PHONE_NUMBER] [varchar](256) NULL,
	[TOTAL_ORDERS] [numeric](38, 0) NULL,
	[FIRST_NAME] [varchar](256) NULL,
	[EMAIL] [varchar](256) NULL
 CONSTRAINT [PK_USERS] PRIMARY KEY CLUSTERED 
(
	[USER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];
